### ISSUE TITLE
[FEATURE]: Add a prefix like # for global messages

### ISSUE THREAD

**Issue by thevalleyy** [beanbeanjuice/SimpleProxyChat#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Feature

Only messages that start with a specific prefix (which can be configured) should be sent to other servers

### Are you certain this is a feature request?

- [X] I am certain this is a feature request, not an improvement request, bug report, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Will add this in the next update! It's a very good idea
