### ISSUE TITLE
[FEATURE]: Configuration on how to cast messages in prefix mode

### ISSUE THREAD

**Issue by thevalleyy** [beanbeanjuice/SimpleProxyChat#127]
### Feature

- [X] I have searched the existing issues and not found ones relating to my problem.

When in prefix mode, I only want the player with the permission `simpleproxychat.read.chat` to see that messages. but currently they are cast to every online player on the same server as I am through the normal chat.

I request a setting to avoid that prefixed messages are sent in the normal minecraft chat, but rather cast to everyone with the read permission.

### Are you certain this is a feature request?

- [X] I am certain this is a feature request, not an improvement request, bug report, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Hey! Just for clarification;

Let's say `Player1` and `Player3` is in `hub` and `Player2` is in `smp`.

`Player1`: Says "#hi!"
`Player2`: Sees "hi!"
`Player3`: Sees "#hi!"

Are you saying you don't want `Player3` to see the message unless they have the `simpleproxychat.read.chat` message?

**Comment by thevalleyy** [comment]
Yeah that's it! I want the proxychat messages to be shown _only_ to players that have the permission!

**Comment by beanbeanjuice** [comment]
Hey! So I did some research;

This is not possible at all on Velocity.
For BungeeCord it is possible, but only if I am the only plugin on the Proxy unfortunately :(. It seems as though this is how the messages are sent;

In-Game messages -> Proxy

And to my knowledge, unless you have a "helper" plugin also in the spigot/paper server the proxy itself cannot interact directly with stuff in the server, rather it can only send messages to players or kick them from the proxy/send them to another server on the proxy.

I will keep this open, however, if I find a way to do it! This is a very good idea, but cancelling in-game messages are not possible for now :(

**Comment by thevalleyy** [comment]
Hey, thank you for the effort you made.
That helper plugin's only job would be to cancel messages that start with a certain prefix, right? In that case, I think I'm able to code that. 

A config entry to also send messages to players on the same server would help me so much.

Greetings from Germany 🇩🇪

**Comment by beanbeanjuice** [comment]
> Hey, thank you for the effort you made. That helper plugin's only job would be to cancel messages that start with a certain prefix, right? In that case, I think I'm able to code that.
> 
> A config entry to also send messages to players on the same server would help me so much.
> 
> Greetings from Germany 🇩🇪

That would be correct, if you are unable to do that I can code a quick plugin for you and supply you with the code if you need me to!

**Comment by thevalleyy** [comment]
thanks for the nice offer. i'll try it myself first, i'm trying to learn plugins at the moment anyway.

Is there a way for a spigot plugin to get the chat prefix from the velocity plugin?

**Comment by beanbeanjuice** [comment]
> thanks for the nice offer. i'll try it myself first, i'm trying to learn plugins at the moment anyway.
> 
> Is there a way for a spigot plugin to get the chat prefix from the velocity plugin?

I think there is not unfortunately... there would be using "PluginMessaging" but that would make things very slow.
I think the only way to do it is to hard-code it or to make a config.yml that mirrors the same prefix!
