### ISSUE TITLE
[BUG]: Version 0.3.7 no Discord to MC

### ISSUE THREAD

**Issue by SonnenPingu** [beanbeanjuice/SimpleProxyChat#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Version

0.3.7

### What proxy software are you seeing this issue on?

Velocity

### What proxy software version are you using?

newest version

### Current Behaviour

If you are using version 0.3.7.

The Discord chat is no longer displayed on MC.

If you use 0.3.5 it works perfectly.

Unfortunately no erros or so visible

### Expected Behaviour

It should bring the chat from Discord to Minecraft

### Steps to Reproduce

Update VeloCity.
Backend runs on paper 1.20.4
Install version 0.3.5 and set it up.

Write in the DC chat it arrives in MC.

Update to 0.3.7 and repeat the whole thing and you will see that nothing arrives.

### Are you certain this is a bug report?

- [X] I am certain this is a bug report, and not a feature request, improvement request, or a security vulnerability.

**Comment by beanbeanjuice** [comment]
I'll fix this soon!
