### ISSUE TITLE
[BUG]: Increase Timer on Channel Topic

### ISSUE THREAD

**Issue by SonnenPingu** [beanbeanjuice/SimpleProxyChat#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Version

0.5.2

### What proxy/server software are you seeing this issue on?

Velocity

### What proxy software version are you using?

3.3.3 Velocity

### Current Behaviour

[07:15:15 WARN] [com.beanbeanjuice.simpleproxychat.libs.net.dv8tion.jda.api.requests.RestRateLimiter]: Encountered 429 on route PATCH/channels/{channel_id} with bucket 6e836da6cef38ba2f3dfd8568a4e9631:channel_id=1122886425545818232 Retry-After: 1000 ms Scope: shared

### Steps to Reproduce

wouldn't know how to replicate that 

### Are you certain this is a bug report?

- [X] I am certain this is a bug report, and not a feature request, improvement request, or a security vulnerability.

**Comment by SonnenPingu** [comment]
This is only about whether this can be ignored or what the exact reason is

**Comment by beanbeanjuice** [comment]
I see, I will fix this soon.
