### ISSUE TITLE
[FEATURE]: Show total players online in Discord status

### ISSUE THREAD

**Issue by uberswe** [beanbeanjuice/SimpleProxyChat#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Feature

I have been using this mod before moving to a setup using a proxy: https://www.curseforge.com/minecraft/mc-mods/dcintegration

It would be really nice if I could show the current count of players online for all servers in the status as that is one thing I miss having.

### Are you certain this is a feature request?

- [X] I am certain this is a feature request, not an improvement request, bug report, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Hey, just to confirm... you mean in this attached image right? You want the player count to be visible here?

![image](https://github.com/user-attachments/assets/ae91ea54-6343-461f-8f35-5c2fca5593a2)

Where it says "Playing Minecraft" you want it to basically say something like... "Watching 3/100 players." or something like that?

**Comment by uberswe** [comment]
Yes exactly, even better if it can be customized. Here is a current example off my discord bots
<img width="231" alt="Screenshot 2024-07-18 at 00 48 47" src="https://github.com/user-attachments/assets/50f2c4df-5153-4ee2-83f1-dbcc08f62c85">

**Comment by uberswe** [comment]
Thanks for the quick update!
