### ISSUE TITLE
[FEATURE]: Webhook mode for messages to Discord

### ISSUE THREAD

**Issue by yeahimman** [beanbeanjuice/SimpleProxyChat#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Feature

Hi! Below is my suggestion for a feature.

A webhook mode for Server to Discord messages, kind of like what DiscordSRV does. Below I'll add the image of how it looks.

Having everything in embeds makes the chat more bulky, also embeds aren't supported in notifications for phones. I hope this isn't too tough to add, or this feature already exists ( I couldn't find a mention of it. )

![image](https://github.com/user-attachments/assets/c35538c5-93fe-4ca7-b47e-a32c93de19a9)

### Are you certain this is a feature request?

- [X] I am certain this is a feature request, not an improvement request, bug report, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
I think this is a good idea! I'll add it soon.

**Comment by elliotnash** [comment]
I think this should be reopened – my understanding #221 only adds the ability to send non embed messages through the bot. Sending non embed messages through a bot does not have feature parity with a webhook. For example webhooks allow you to change the name and avatar on a per message basis, which allows user's skins to be used as the discord avatar.
