### ISSUE TITLE
[BUG]: Usernames not escaped in markdown

### ISSUE THREAD

**Issue by LilyKensa** [beanbeanjuice/SimpleProxyChat#219]
For example, the minecraft username `a_cool_guy` will result in a<i>cool</i>guy, you need to escape it like `a\_cool\_guy`

**Comment by LilyKensa** [comment]
Oh wait but if the username is wrapped in a `code` like this, the username should not be escaped...

Maybe provide another placeholder like `%escaped_username%`?

**Comment by beanbeanjuice** [comment]
I see, placeholder route is probably best. Should be simple enough to add! I had no clue so thank you so much!
