### ISSUE TITLE
[FEATURE]: Permission to receive messages in general

### ISSUE THREAD

**Issue by thevalleyy** [beanbeanjuice/SimpleProxyChat#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues and not found ones relating to my problem.

### Feature

A permission like `simpleproxychat.read.chat` that all users need, if they want to receive chat messages across servers.

### Are you certain this is a feature request?

- [X] I am certain this is a feature request, not an improvement request, bug report, or security vulnerability report.

**Comment by beanbeanjuice** [comment]
Will add this in the next update!
